# "org" ensures this Service is used with the correct Serverless Framework Access Key.
#org: mafaia9or10
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: mafia9or10
service: mafia9or10
frameworkVersion: '4.1.5'

stages:
  default:
    resolvers:
      aws-account-1:
        type: aws
        region: us-west-2
        accessKeyId: ${env:ACCOUNT1_AWS_ACCESS_KEY_ID}
        secretAccessKey: ${env:ACCOUNT1_AWS_SECRET_ACCESS_KEY}
        dashboard: false

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

package:
  patterns:
    - '!node_modules/serverless-offline/**'
    - '!node_modules/serverless-dotenv-plugin/**'
    - '!node_modules/java-invoke-local/**'
    - '!node_modules/@esbuild/**'
    - '!node_modules/luxon/**'
    - '!node_modules/@hapi/**'
    - '!node_modules/velocityjs/**'
    - '!node_modules/jsonpath-plus/**'
    - '!node_modules/jszip/**'
    - '!node_modules/jose/**'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  environment:
    S3_BUCKET: mafia9or10-avatars
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: arn:aws:s3:::mafia9or10-avatars/*

functions:
  api:
    timeout: 30
    memorySize: 1024
    handler: handler.handler
    events:
      - httpApi: "*"
#      - http:
#          path: /
#          method: ANY
#          cors: true
#      - http:
#          path: /{proxy+}
#          method: ANY
#          cors: true